api:
    resource: "@APIBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

users:
    type: rest
    resource: APIBundle\Controller\UsersController